### PR TITLE
[feature] support OpenGL 3

### PR DESCRIPTION
**Pull request by claudeha**
Not ready to be merged yet, comments appreciated.

This enables OpenGL 3.3 Compatibility profle support at compile time, by wrapping all the OpenGL 4 specific parts in `#ifdef USE_OPENGL_4`.

However, there is currently no way to `#define USE_OPENGL_4` in the build system, I need to learn more about CMake to fix that.

It is a compile time flag because of the inheritance from `QOpenGLFunctions` etc.  Maybe there would be a way to dynamically switch between creating one or the other at runtime, I don't know Qt so I don't know what is possible.

Thoughts?

### CODE REVIEW

**Comment by 3Dickulus** [comment]
I have wrapped different GL version calls... for instance... around line 320 in DisplayWidget.cpp
```
            if (context()->format().majorVersion() > 2 || context()->format().profile() == QSurfaceFormat::CompatibilityProfile) {
                glGenerateMipmap(GL_TEXTURE_2D); // Generate mipmaps here!!!
            }
            else {
                glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, GL_TRUE); // Generate mipmaps here!!!
            }
```
I spent a lot of time testing under different versions and wrapped all conflicts like this or similar.
The default, GL4.1 compatibility, encompasses GL3.3 so again, not sure where you are going with this ???

**Comment by claudeha** [comment]
otherwise it crashes on startup in `initializeGL` (possibly inside Qt, haven't managed to get a decent trace)

**Comment by 3Dickulus** [comment]
if it compiles that indicates that all gl calls are available or it wouldn't successfully link with the libs
moving the executable to another machine with lower grade gfx card or different drivers/libs and it would not be expected to run properly

It sounds like I missed a call or maybe not testing GL version properly, and I have to say that FragM 2.5.0 is not really intended to run on hw that is  not capable of at least GL4.1

**Comment by 3Dickulus** [comment]
`#ifdef USE_OPENGL_4 (but no way of defining it yet)`

in CMakeLists.txt

```
# ON if you want opengl 4+ capabilities
OPTION ( USE_OPENGL_4 "Build with OpenGL 4.1" ON)
```

**Comment by 3Dickulus** [comment]
oh... you meant defining it at runtime rather than compile time? in that case it has to be compiled with GL4.1 compatibility so that all functions are available, then at runtime check the version and profile type that Qt (in all it's wisdom) decided to use. deja vous have we been here before? I recall asking Qt for specific versions and profiles but it's not guaranteed to return exactly what is requested :-/

**Comment by claudeha** [comment]
> I have to say that FragM 2.5.0 is not really intended to run on hw that is not capable of at least GL4.1

Ok.  I do still want to use FragM on my ancient laptop while travelling, so I will keep this fork alive even if you won't merge it.

> otherwise it crashes on startup

possibly this might be down to my Mesa version overrides, will check later...

**Comment by 3Dickulus** [comment]
I do think it's a good idea to be able to use the GL version that matches the intended target, fi when developing fragment code for another device, so I'm not discounting this idea.

**Comment by claudeha** [comment]
Ok I merged master branch and added the CMake fixes.  master branch (and this branch compiled with OpenGL 4) still crashes on launch inside Qt (on laptop without any Mesa environment overrides).  This page has some tips how to get backtrace with library info on Debian Buster: <https://michael.stapelberg.ch/posts/2019-02-15-debian-debugging-devex/>.  This is where it crashes on launch:

```
Thread 1 "Fragmentarium-2" received signal SIGSEGV, Segmentation fault.
QOpenGLFunctions_4_1_Compatibility::glGetString (this=0x555555c24c00, name=7936) at /usr/include/x86_64-linux-gnu/qt5/QtGui/qopenglfunctions_4_1_compatibility.h:1088
1088        return d_1_0_Core->f.GetString(name);
(gdb) list
1083        d_1_0_Core->f.GetTexImage(target, level, format, type, pixels);
1084    }
1085
1086    inline const GLubyte * QOpenGLFunctions_4_1_Compatibility::glGetString(GLenum name)
1087    {
1088        return d_1_0_Core->f.GetString(name);
1089    }
1090
1091    inline void QOpenGLFunctions_4_1_Compatibility::glGetIntegerv(GLenum pname, GLint *params)
1092    {
(gdb) up
#1  0x00005555555eb454 in Fragmentarium::GUI::DisplayWidget::initializeGL (this=0x555555c24bd0) at /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:99
99          vendor = QString ( ( char * ) glGetString ( GL_VENDOR ) );
(gdb) list
94      void DisplayWidget::initializeGL()
95      {
96
97          initializeOpenGLFunctions();
98
99          vendor = QString ( ( char * ) glGetString ( GL_VENDOR ) );
100         renderer = QString ( ( char * ) glGetString ( GL_RENDERER ) );
101         glvers = QString ( ( char * ) glGetString ( GL_VERSION ) );
102         /// test for nVidia card and set the nV flag
103         foundnV = vendor.contains ( "NVIDIA", Qt::CaseInsensitive );
(gdb) down
#0  QOpenGLFunctions_4_1_Compatibility::glGetString (this=0x555555c24c00, name=7936) at /usr/include/x86_64-linux-gnu/qt5/QtGui/qopenglfunctions_4_1_compatibility.h:1088
1088        return d_1_0_Core->f.GetString(name);
(gdb) print *this
$1 = {<QAbstractOpenGLFunctions> = {_vptr.QAbstractOpenGLFunctions = 0x5555557114a0 <vtable for Fragmentarium::GUI::DisplayWidget+552>, d_ptr = 0x555555c25570}, d_1_0_Core = 0x0, d_1_1_Core = 0x0, d_1_2_Core = 0x0, 
  d_1_3_Core = 0x0, d_1_4_Core = 0x0, d_1_5_Core = 0x0, d_2_0_Core = 0x0, d_2_1_Core = 0x0, d_3_0_Core = 0x0, d_3_1_Core = 0x0, d_3_2_Core = 0x0, d_3_3_Core = 0x0, d_4_0_Core = 0x0, d_4_1_Core = 0x0, d_1_0_Deprecated = 0x0, 
  d_1_1_Deprecated = 0x0, d_1_2_Deprecated = 0x0, d_1_3_Deprecated = 0x0, d_1_4_Deprecated = 0x0, m_reserved_2_0_Deprecated = 0x0, d_3_3_Deprecated = 0x0}
(gdb) bt
#0  QOpenGLFunctions_4_1_Compatibility::glGetString (this=0x555555c24c00, name=7936) at /usr/include/x86_64-linux-gnu/qt5/QtGui/qopenglfunctions_4_1_compatibility.h:1088
#1  0x00005555555eb454 in Fragmentarium::GUI::DisplayWidget::initializeGL (this=0x555555c24bd0) at /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:99
#2  0x00007ffff76d994a in QOpenGLWidgetPrivate::initialize (this=0x555555c24ed0) at kernel/qopenglwidget.cpp:852
#3  0x00007ffff76d9fd2 in QOpenGLWidget::resizeEvent (this=0x555555c24bd0, e=<optimized out>) at kernel/qopenglwidget.cpp:1272
#4  0x00007ffff76b9f6e in QWidget::event (this=0x555555c24bd0, event=0x7fffffffd690) at kernel/qwidget.cpp:9066
#5  0x00007ffff767b4b1 in QApplicationPrivate::notify_helper (this=this@entry=0x555555bdf0d0, receiver=receiver@entry=0x555555c24bd0, e=e@entry=0x7fffffffd690) at kernel/qapplication.cpp:3726
#6  0x00007ffff7682950 in QApplication::notify (this=0x55555572f6b0, receiver=0x555555c24bd0, e=0x7fffffffd690) at kernel/qapplication.cpp:3485
#7  0x00007ffff694e5a9 in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x555555c24bd0, event=event@entry=0x7fffffffd690)
    at ../../include/QtCore/5.11.3/QtCore/private/../../../../../src/corelib/thread/qthread_p.h:307
#8  0x00007ffff76b207b in QCoreApplication::sendEvent (event=0x7fffffffd690, receiver=0x555555c24bd0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#9  QWidgetPrivate::sendPendingMoveAndResizeEvents (this=this@entry=0x555555c24ed0, recursive=recursive@entry=false, disableUpdates=<optimized out>, disableUpdates@entry=false) at kernel/qwidget.cpp:7935
#10 0x00007ffff76b5f83 in QWidgetPrivate::show_helper (this=0x555555c24ed0) at kernel/qwidget.cpp:7986
#11 0x00007ffff76b5de1 in QWidgetPrivate::show_recursive (this=<optimized out>) at kernel/qwidget.cpp:7916
#12 0x00007ffff76b5f22 in QWidgetPrivate::showChildren (this=this@entry=0x555555c242f0, spontaneous=spontaneous@entry=false) at ../../include/QtCore/../../src/corelib/global/qglobal.h:1038
#13 0x00007ffff76b5f9f in QWidgetPrivate::show_helper (this=this@entry=0x555555c242f0) at kernel/qwidget.cpp:7992
#14 0x00007ffff76b912b in QWidget::setVisible (this=0x555555c242b0, visible=<optimized out>) at kernel/qwidget.cpp:8341
#15 0x00007ffff76b5f38 in QWidgetPrivate::showChildren (this=this@entry=0x555555e58880, spontaneous=spontaneous@entry=false) at kernel/qwidget.cpp:8424
#16 0x00007ffff76b5f9f in QWidgetPrivate::show_helper (this=this@entry=0x555555e58880) at kernel/qwidget.cpp:7992
#17 0x00007ffff76b912b in QWidget::setVisible (this=0x555555e3c3f0, visible=<optimized out>) at kernel/qwidget.cpp:8341
#18 0x00007ffff76b5f38 in QWidgetPrivate::showChildren (this=this@entry=0x555555c227f0, spontaneous=spontaneous@entry=false) at kernel/qwidget.cpp:8424
#19 0x00007ffff76b5f9f in QWidgetPrivate::show_helper (this=this@entry=0x555555c227f0) at kernel/qwidget.cpp:7992
#20 0x00007ffff76b912b in QWidget::setVisible (this=0x555555c22420, visible=<optimized out>) at kernel/qwidget.cpp:8341
#21 0x00005555555dd380 in main (argc=1, argv=0x7fffffffe128) at /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/Main.cpp:190
```

Unfortunately there seem to be missing debug info for the kernel/qwidget stuff, so I can't see what it is doing around `initializeGL()`

This feature branch compiled without OpenGL4 works correctly on my laptop without Mesa overrides and reports:

```
Vendor: NVIDIA Corporation
Renderer: GeForce G 105M/PCIe/SSE2
GL Driver: 3.3.0 NVIDIA 340.107
Using GL 3.3 Compatibility profile
```

**Comment by claudeha** [comment]
I think this can be merged, as `USE_OPENGL_4` is a compile time option enabled by default.

**Comment by 3Dickulus** [comment]
hmm... I hope the conflict resolving went well. it said one file was in conflict so I followed the steps in githelp for resolving simple conflicts... says Merge branch 'master' into feature-support-opengl-3 
I think it only affected the CMakeLists.txt ???

**Pull request merged**
