### PR TITLE
Rotation 2d

### PR DESCRIPTION
**Pull request by GreggHelt2**
Adds rotation parameter for 2D fractals that use Progressive2D.frag

### CODE REVIEW

**Comment by 3Dickulus** [comment]
This appears to have the right stuff in the right places. I will test run the code changes before merging with master and check to see that there aren't any pending commits from me that might conflict, on initial inspection it looks good. I've been meaning to add more comments too, tnx.

**Comment by 3Dickulus** [comment]
After some testing I find that the changes to cpp files are not needed at all for rotation functionality only changes to 2D. frag are required. So to avoid adding clutter to the mess I've already made of FragM sources I am closing this pull request. If you can re submit the request as a "frag only" modification I will reconsider, also, please make the mod to all frags in Examples/Include used by 2D frags.

**Comment by 3Dickulus** [comment]
Still getting to know github :-/
Re-opening.
If you can modify your changes so that they are just added comments and fragment changes I would be happy to merge this pull request.

**Comment by GreggHelt2** [comment]
Thanks, I'll take another look. Should have time tomorrow.

**Comment by GreggHelt2** [comment]
Yep, the actual 2D rotation implemented in these commits does work via only modifications to Progressive2D.frag itself. The problem with only doing that though is how non-zero rotation affects navigation -- without factoring camera rotation into navigation, moving up/down/left/right will be relative to absolute scene axes rather then camera-centric axes. Which means that with non-zero rotation both keyboard and mousedrag navigation will be messed up. The changes to CameraControl.cpp and CameraControl.h are to factor rotation parameter into camera navigation to get the expected behavior. I could probably redo these CameraControl.cpp mods using QTransform for the rotation (similar to how QMatrix4x4 is used for 3D rotations), which I think would make the mods a bit cleaner by pushing the rotation trig details down into a QTransform.rotate() call. What do you think?

**Comment by GreggHelt2** [comment]
Oh, forgot one thing in my last comment: the small change I made to MainWindow.cpp was only to mimic with Rotation parameter how Center and Zoom parameters are already handled there. I wasn't sure if this was needed or not. If you think it is not necessary I'll revert that change.

**Comment by 3Dickulus** [comment]
uhm yes, jumped the gun a bit, it is necessary, trig in CameraControl.cpp, if you can use QtTransform then yes to that as well, will have to test using tiled rendering etc. this leads me to talk of engine rewrite, but in the meantime...
Add a bool option, " Key Movement - Scene or Camera relative", in PreferencesDialog.ui, use designer-qt5, and the load/save calls in PreferencesDialog.h.
Then you should be able to query the QSettings object for the current value of the bool flag from Camera2D::parseKeys() or anywhere else it's needed.

In MainWindow.cpp the treatment of Zoom and Center for 2D and FOV, Eye, Target and Up for 3D is to ensure that we have the minimum requirements for rendering, and creating camera/target paths in 3D.  2D frags that don't use Rotation or Progressive rendering will still have to work so the code shouldn't fail if Rotation doesn't exist.

**Comment by 3Dickulus** [comment]
uhm yes, jumped the gun a bit, it is necessary, trig in CameraControl.cpp, if you can use QtTransform then yes to that as well, will have to test using tiled rendering etc. this leads me to talk of engine rewrite, but in the meantime...
Add a bool option, " Key Movement - Scene or Camera relative", in PreferencesDialog.ui, use designer-qt5, and the load/save calls in PreferencesDialog.h.
Then you should be able to query the QSettings object for the current value of the bool flag from Camera2D::parseKeys() or anywhere else it's needed.

In MainWindow.cpp the treatment of Zoom and Center for 2D and FOV, Eye, Target and Up for 3D is to ensure that we have the minimum requirements for rendering, and creating camera/target paths in 3D.  2D frags that don't use Rotation or Progressive rendering will still have to work so the code shouldn't fail if Rotation doesn't exist.

**Comment by 3Dickulus** [comment]
This needs more testing

**Pull request merged**
