### PR TITLE
[bugfix] line pragma

### PR DESCRIPTION
**Pull request by claudeha**
Fixes: <https://github.com/3Dickulus/FragM/issues/52>

Tested on AMD RX 580 (Mesa, Linux).

### CODE REVIEW

**Comment by 3Dickulus** [comment]
improving sqrt with Newton Raphson gets thumbs up :)

Q: is the overloading thing universal or is it specific to Mesa?

**Comment by 3Dickulus** [comment]
It would be preferable for the log to get copied into a QStringList and then replace the file numbers with file names and then pass each line to WARN() separately? This would make the log lines clickable one by one and put the filename where it should be, I don't like the idea of dumpFileMap();

**Comment by 3Dickulus** [comment]
re:7e4a29e

use `fs->sourceFileNames.indexOf(originalFileName)`
instead of `sf`
in lines 122 and 126

**Comment by 3Dickulus** [comment]
replace `dumpFileMap()` with `createErrorLineLog( QString message, QString log, bool infoOrWarn )`

this function should take the arguments that are currently passed to WARN() and INFO() calls for reporting error lines + the bool for info or warn type.
it should parse the log and create "meaningful" entries ie:filename and error line number and call WARN() or INFO() for each one.

I can see it in my head but haven't the time to do it immediately, click+open file+jump to line, from the log window.

**Comment by 3Dickulus** [comment]
ok have working void DisplayWidget::createErrorLineLog ( QString message, QString log, bool infoOrWarn )

will clean it up tomorrow g'night...

**Comment by claudeha** [comment]
> use `fs->sourceFileNames.indexOf(originalFileName)`
> instead of `sf`

this change would break if the same file is included more than once (which I actually have an idea to do at some point so that Complex.frag can have float and double versions without duplicating the code)

**Comment by 3Dickulus** [comment]
ok have working void DisplayWidget::createErrorLineLog ( QString message, QString log, bool infoOrWarn )

because the filename comes from the index of the nth file included it should be fine, if complex.frag is the 2nd file included and then again as the 4th file included this would make the error line read NthFilename and NthLine ... the filename is the same for 2nd and 4th so I'm not seeing a problem in theory, practice may prove me wrong though.

**Comment by 3Dickulus** [comment]
oh, and I'm using the first capture from `QRegExp testamd ( "^([0-9]+)[:]([0-9]+)[(]" );` ([0-9]+) as index for filename so I believe it will be fine if the same file is included more than once

**Pull request merged**
