### PR TITLE
refactor Complex.frag to support both float and double

### PR DESCRIPTION
**Pull request by claudeha**
- new DoubleMath.frag for double precision trig etc

  - copy/pasted from old Complex.frag

  - _builtin_* captures for overloading (built in functions
    can be redefined but not overloaded directly)

- new ComplexBase.frag for (dual) complex maths using
  REAL, VEC2, VEC3, VEC4 (number type agnostic)

- Complex.frag is now a simple skeleton, that includes the
  above two.  If double is supported (tested by
  `__VERSION__ >= 400`) then REAL etc are redefined to the
  double precision variants and ComplexBase is included
  again.

- User frags that wish to support both float and double
  (using highest precision available) should set #version
  and use REAL VEC2 etc.  Then the only thing that needs
  to be changed to support old hw is the #version.

- User frags that wish to use both float and double at the
  same time should use float, vec2 for low precision and
  REAL, VEC2 for high precision.  This will gracefully
  downgrade to float for both if double is not supported.

- If user frags absolutely need double precision, then
  `#version 400 compatibility` and just use double, dvec2,
  etc.

- Tested briefly with `BurningShip.frag`, adding a #version
  line doesn't break it horribly.  `DoubleTest.frag` also
  works fine.

Closes: https://github.com/3Dickulus/FragM/issues/67

### CODE REVIEW

**Comment by claudeha** [comment]
Not perfect yet.  Needs some work w.r.t. "float functions not defined in earlier GLSL versions" (cosh and friends).

**Comment by 3Dickulus** [comment]
Hats off to you, that is quite the piece of fragment code!
Implementing something that the GPU manufacturers should have done, cheers!

You've given me a lot of stuff to look at and test... I should be through it by next week.

**Comment by 3Dickulus** [comment]
so... include ComplexBase.frag once for float stuff and if vers > 400 include ComplexBase.frag again for the rest of the double stuff and oveloads etc...

I'm wondering if including the same file twice is compatible with the error line reporting? did you check this or notice any discrepancy while hacking it together?

In my FragMTestSuite/Error-Line-Tests I'm only testing vertex and fragment parts in mainshader and buffershader, no auxiliary code beyond MathUtils.frag

**Comment by claudeha** [comment]
Working on this a bit more today:

- Added more functions for GLSL < 130 (though my Trudy test frags don't work that far back because I already changed my camera `varying` to `out`, consider this experimental...) and some additional overloads for >= 400 (mainly sinh, cosh, tanh, but perhaps some others too)
- Renamed DoubleMath.frag to Math.frag as it's not just Double, and it can now be included safely in earlier versions than 400 too
- The double-include doesn't seem to cause problems with frag export when rendering (I seem to recall an error in the past, but it works fine now).
- The double-include seems ok with error line reporting (maybe off by one or two lines, but that seems normal for GLSL syntax errors that I introduce anywhere) for frags included before or after Complex.frag, and also within Complex.frag between the double-include of ComplexBase.frag.

force-pushing the code here shortly

**Comment by 3Dickulus** [comment]
This sounds great! Is it ready to be released into the wild?

**Comment by 3Dickulus** [comment]
ok, squash and merge, this is all in the Examples/Includes folder so shouldn't be a problem when merging gl4dev->Development->master

**Pull request merged**
