### PR TITLE
[bugfix] AMD/Mesa GLSL

### PR DESCRIPTION
**Pull request by claudeha**
Fixes: https://github.com/3Dickulus/FragM/issues/62

AMD/Mesa has some small issues/bugs with the GLSL, some of which may be bugs in the driver but others are probably that it is more specification-compliant than some other lax drivers that accept almost anything.

I think I fixed all of them apart from something in `Include/DE-Raytracer-Slicer.frag` that misses some varyings.

### CODE REVIEW

**Comment by 3Dickulus** [comment]
wow, you've been busy, I never tackled this because my mathematical aptitude is just enough to mess things up really good ;)

**Comment by 3Dickulus** [comment]
spec compliance issues nailed down? I'll merge when you're ready.

**Comment by claudeha** [comment]
I think this is ready to merge.  If you're anxious, try doing a test-suite run with this branch vs master branch to see if there are any image differences?

**Comment by claudeha** [comment]
`git blame` can output per-line last-modification information, if you have git sources.  Otherwise a single line in the frag saying "last updated for FragM 2.5.0.190828" might be useful.  This is what the music software Pure-data does in its help files.

**Pull request merged**
